apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service  
  namespace: portal
  labels:
    app: nginx
spec:
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort

